# Generated by Django 4.0.6 on 2022-07-17 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereport',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating del Informe'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='aerial_game',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Juego aéreo'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='anticipating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Anticipación'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='arrival_baseline',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Llegada a línea de fondo'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='back_movement',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Carrera hacia atrás'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='box_to_box_ability',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Habilidad box to box'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='build_up_capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Capacidad creativa'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='command_of_defence',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Mando sobre la defensa'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='composture_on_the_ball',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Serenidad con balón'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='covering_depth',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Cobertura de profundidad'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='coverings',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='dealing_with_offside',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Control del fuera de juego'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='decision_making',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Toma de decisiones'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='defensive_capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Capacidad defensiva'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='determined',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Determinación/Agresividad'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='dynamism',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Dinamismo'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_aerial_game',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Juego por alto/Salidas'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_box_domain',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Dominio del área'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_comunication',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Comunicación con la defensa'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_crosses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Control de centros laterales'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_footwork',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Juego con los pies'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_goal_kicks',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Saque de puerta'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_grip',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Agarre del balón'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_one_to_one',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Uno contra uno'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_penalty_saves',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Paradas de penalti'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='gk_saves',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Paradas'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='height',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Talla/Altura'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='hold_up_play',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Aguantar el balón'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='intelligence',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Inteligencia'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='key_passing',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Pases clave'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='lateral_crosses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Centros laterales'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='lateral_movement',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Movimiento lateral'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='left_foot',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Dominio de pie izquierdo'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='link_up_play',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Juego combinativo'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='long_passing',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Pases largos'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='off_the_ball_movements',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Movimientos sin balón'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='pace',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Ritmo/Velocidad'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='physical_power',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Corpulencia/Fuerza'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='positioning',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Posicionamiento'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='quick_short_distance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Velocidad en corta distancia'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='right_foot',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Dominio de pie derecho'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='shooting',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Disparo/Finalización'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='short_passing',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Pases cortos'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='striking_ability',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Golpeo de balón/ABP'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='tackling',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Entradas'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='technique',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Técnica individual'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='through_passing',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Pases entre líneas'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='traveling_ball',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Conducción de balón'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='trickery',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Regates/Habilidad'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='turns',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Giros/Cambios de dirección'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='vision',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Visión de juego'),
        ),
        migrations.AlterField(
            model_name='performancereport',
            name='work_rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Capacidad de trabajo'),
        ),
    ]
