# Generated by Django 4.0.6 on 2022-07-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='number_players',
            field=models.IntegerField(blank=True, default=0, verbose_name='Jugadores extraídos'),
        ),
    ]
