# Generated by Django 4.0.6 on 2022-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0002_alter_playertransfermarkt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercapology',
            name='ca_player_id',
            field=models.CharField(max_length=150),
        ),
    ]
