# Generated by Django 4.0.6 on 2022-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0003_alter_playertransfermarkt_tm_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransfermarkt',
            name='tm_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertransfermarkt',
            name='tm_contract_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertransfermarkt',
            name='tm_date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
