# Generated by Django 4.0.6 on 2022-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0003_alter_playercapology_ca_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='state',
            field=models.CharField(choices=[('OK', 'Completado'), ('KO', 'Con errores'), ('IN', 'En proceso')], default='IN', max_length=20),
        ),
    ]
