# Generated by Django 4.0.6 on 2022-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0004_alter_scrapejob_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransfermarkt',
            name='tm_height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='playertransfermarkt',
            name='tm_position',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
