# Generated by Django 4.0.6 on 2022-07-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0006_alter_playertransfermarkt_tm_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='origin',
            field=models.CharField(choices=[('FB', 'FB'), ('FG', 'FG'), ('US', 'US'), ('TM', 'TM'), ('CA', 'CA')], default='FB', max_length=2),
        ),
    ]
