# Generated by Django 4.0.6 on 2022-07-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0007_alter_scrapejob_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfbref',
            name='fb_Dist',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
