# Generated by Django 4.0.6 on 2022-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0008_alter_playerfbref_fb_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfbrefgk',
            name='fb_G_plus_A_minus_PK',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
