# Generated by Django 4.0.6 on 2022-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0009_alter_playerfbrefgk_fb_g_plus_a_minus_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfbref',
            name='fb_G_plus_A_minus_PK',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerfbref',
            name='fb_born',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
