# Generated by Django 4.0.6 on 2022-07-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0011_alter_playerfbref_fb_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfbrefgk',
            name='fb_player_id',
            field=models.CharField(max_length=30),
        ),
    ]
