# Generated by Django 4.0.6 on 2022-07-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0013_rename_fb_pk_m_playerfbrefgk_fb_pk_saves_perc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfbrefgk',
            name='fb_born',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
