# Generated by Django 4.0.6 on 2022-07-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='also_named',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='También llamado'),
        ),
    ]
