# Generated by Django 4.0.6 on 2022-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_also_named'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.URLField(default='https://img.a.transfermarkt.technology/portrait/header/default.jpg', max_length=255, verbose_name='Foto del jugador'),
        ),
    ]
