# Generated by Django 4.0.6 on 2022-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id_capology',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_fbref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_transfermarkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_understat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
