# Generated by Django 4.0.6 on 2022-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_id_capology_alter_player_id_fbref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id_transfermarkt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_understat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
