# Generated by Django 4.0.6 on 2022-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_id_transfermarkt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id_capology',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_fbref',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_transfermarkt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_understat',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
