# Generated by Django 4.0.6 on 2022-07-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_remove_goalkeeperstats_ca_salary_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goalkeeperstats',
            constraint=models.UniqueConstraint(fields=('player', 'season', 'team', 'matches_played'), name='unique_player_id_season_team_combination_goalkeepers_cleaned'),
        ),
        migrations.AddConstraint(
            model_name='playerstats',
            constraint=models.UniqueConstraint(fields=('player', 'season', 'team', 'matches_played'), name='unique_player_id_season_team_combination_players_cleaned'),
        ),
    ]
