# Generated by Django 4.0.6 on 2022-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_goalkeeperstats_unique_player_id_season_team_combination_goalkeepers_cleaned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='index_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Index'),
        ),
    ]
