# Generated by Django 4.0.6 on 2022-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_index_index_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Index', 'verbose_name_plural': 'Index'},
        ),
        migrations.AlterField(
            model_name='index',
            name='index_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Index'),
        ),
    ]
