# Generated by Django 4.0.6 on 2022-07-16 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_remove_scoring_active_remove_scoring_index_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='index',
            name='index_name',
            field=models.CharField(help_text='Máximo 6 caracteres', max_length=6, unique=True, verbose_name='Nombre del Index'),
        ),
        migrations.AlterField(
            model_name='scoringrequest',
            name='minutes_played_min',
            field=models.IntegerField(default=600, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(90)]),
        ),
    ]
