# Generated by Django 4.0.6 on 2022-07-16 15:10

from django.conf import settings
from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0014_remove_scoringrequest_user_alter_index_index_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(players.models.getUser), to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
