# Generated by Django 4.0.6 on 2022-07-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_scoringrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringrequest',
            name='user',
        ),
    ]
