# Generated by Django 4.0.6 on 2022-07-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_remove_scoringrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringrequest',
            name='season_request',
            field=models.CharField(default='2021-2022', max_length=50),
        ),
    ]
