# Generated by Django 4.0.6 on 2022-07-16 20:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_alter_scoringrequest_season_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoring',
            options={'get_latest_by': '-calculate_date', 'ordering': ['scoring'], 'verbose_name': 'Scoring', 'verbose_name_plural': 'Scorings'},
        ),
        migrations.CreateModel(
            name='SimilarityRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la petición')),
                ('minutes_played_min', models.IntegerField(default=600, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(90)])),
                ('season_request', models.CharField(default='2021-2022', max_length=50)),
                ('index_used', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='players.index', verbose_name='Index usado')),
            ],
            options={
                'verbose_name': 'Cálculo de Similaridad',
                'verbose_name_plural': 'Cálculos de Similaridad',
            },
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity', models.FloatField(verbose_name='Similitud')),
                ('calculate_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cálculo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Jugador')),
                ('similar_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_player', to='players.player', verbose_name='Jugador similar')),
                ('similarity_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.similarityrequest', verbose_name='Petición de actualización de Similitud')),
            ],
            options={
                'verbose_name': 'Análisis de Similitud',
                'verbose_name_plural': 'Análisis de Similitud',
                'ordering': ['player', '-similarity'],
                'get_latest_by': '-calculate_date',
            },
        ),
    ]
