# Generated by Django 4.0.6 on 2022-07-17 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_alter_scoring_options_similarityrequest_similarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoring',
            options={'get_latest_by': '-calculate_date', 'ordering': ['-scoring'], 'verbose_name': 'Scoring', 'verbose_name_plural': 'Scorings'},
        ),
        migrations.AlterField(
            model_name='scoringrequest',
            name='minutes_played_min',
            field=models.IntegerField(default=600, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(90)], verbose_name='Mínimo de minutos jugados'),
        ),
        migrations.AlterField(
            model_name='scoringrequest',
            name='season_request',
            field=models.CharField(default='2021-2022', max_length=50, verbose_name='Temporada del cálculo'),
        ),
    ]
